language: go

go:
  - 1.6

install:
  - wget -O docker-machine https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-Linux-x86_64
  - chmod +x docker-machine
  - export PATH=$PWD:$PATH
  - make vendor

script:
  - make test

notifications:
  email: false
